<?php
$sHelper = $this->helper('ITM\Sportires\Helper\Data');
$tire_width_collection  = $sHelper->getAttributeOptions("moto_tire_width");
$tire_ratio_collection  = $sHelper->getAttributeOptions("moto_tire_ratio");
$tire_diameter_collection  = $sHelper->getAttributeOptions("moto_tire_diameter");

?>
<form data-mage-init='{"validation": {}}' class="form " action="<?= $this->getUrl("sportires/product/filterlist")?>" id="moto-form" method="get" autocomplete="off">
    <input type="hidden" name="type" value="moto">

    <fieldset class="fieldset">
        <div class="field required">
            <div class="row">
				<div class="col-12 col-md-4 col-lg-4">
					<label class="text-333"><?= __("Ancho")?> <span class="indicador">[A]</span>:</label>
					<div data-block="dropdown-moto-width" class="select-container">
						<input readonly class="custom-select mr-sm-2 action"  value="" placeholder="<?= __("Elegir")?>"  id="moto_tire_width" name="tire1" data-trigger="triggg1"  data-validate="{required:true}" >
						<input type="hidden" name="moto_tire_width" id="moto-width-input" value >
					</div>
					<div  class="block block-container-moto-width" style="display:none"
						 data-mage-init='{
							"dropdownDialog": {
								"appendTo": "[data-block=dropdown-moto-width]",
								"triggerTarget":"[data-trigger=triggg1]",
								"timeout": 2000,
								"closeOnMouseLeave": false,
								"closeOnEscape": true,
								"autoOpen": false, 
								"triggerClass": "active",
								"parentClass": "active",
							
								"buttons": []
							}
						 }' > 
						<div  id="option-container-moto-width">
							<span class="tittle"><?=__("Ancho")?></span>
						<a title="Close" class="fancybox-item fancybox-close close fancybox-newsletter-close"></a>
							<ul id="altselect-moto-width" class="row altselect" >
									<li>
										<span data-bind=""><?=__("None")?></span>
									</li>
							<?php foreach ($tire_width_collection as $item ):?>
									<li>
										<span data-bind="<?= $item["value"]?>"><?= $item["label"]?></span>
									</li>
							<?php endforeach;?>
		
							</ul>
						</div>
					</div> 
				</div> 

				<div class="col-12 col-md-4 col-lg-4">				
					<label class="text-333"><?= __("Serie")?> <span class="indicador">[B]</span>:</label>
					<div data-block="dropdown-moto-ratio" class="select-container">
						<input readonly class="custom-select mr-sm-2 action"  value="" placeholder="<?= __("Elegir")?>"  id="moto_tire_ratio" name="tire2" data-trigger="triggg2"  data-validate="{required:true}" >
						<input type="hidden" name="moto_tire_ratio" id="moto-ratio-input" value >
					</div>
					<div  class="block block-container-moto-ratio"  style="display:none"
						 data-mage-init='{
							"dropdownDialog": {
								"appendTo": "[data-block=dropdown-moto-ratio]",
								"triggerTarget":"[data-trigger=triggg2]",
								"timeout": 2000,
								"closeOnMouseLeave": false,
								"closeOnEscape": true,
								"autoOpen": false, 
								"triggerClass": "active",
								"parentClass": "active",
							
								"buttons": []
							}
						 }' > 
						<div  id="option-container-moto-ratio">
							<span class="tittle"><?=__("Serie")?></span>
						<a title="Close" class="fancybox-item fancybox-close close fancybox-newsletter-close"></a>
							<ul id="altselect-moto-ratio" class="row altselect" >
									<li>
										<span data-bind=""><?=__("None")?></span>
									</li>
							<?php foreach ($tire_ratio_collection as $item ):?>
									<li>
										<span data-bind="<?= $item["value"]?>"><?= $item["label"]?></span>
									</li>
							<?php endforeach;?>
							</ul>
						</div>
					</div>
				</div>
				
				<div class="col-12 col-md-4 col-lg-4">				
					<label class="text-333"><?= __("Rin")?> <span class="indicador">[C]</span>:</label>
					<div data-block="dropdown-moto-diameter" class="select-container">
						<input readonly class="custom-select mr-sm-2 action" value="" placeholder="<?= __("Elegir")?>"  id="moto_tire_diameter"  name="tire3" data-trigger="triggg3"  data-validate="{required:true}" >
						<input type="hidden" id="moto-diameter-input" name="moto_tire_diameter" value >
					</div> 
					<div  class="block block-container-moto-diameter"  style="display:none"
						 data-mage-init='{
							"dropdownDialog": {
								"appendTo": "[data-block=dropdown-moto-diameter]", 
								"triggerTarget":"[data-trigger=triggg3]",
								"timeout": 2000,
								"closeOnMouseLeave": false,
								"closeOnEscape": true,
								"autoOpen": false, 
								"triggerClass": "active",
								"parentClass": "active",
							
								"buttons": []
							}
						 }' > 
						<div  id="option-container-moto-diameter">
							<span class="tittle"><?=__("Rin")?></span>
						<a title="Close" class="fancybox-item fancybox-close close fancybox-newsletter-close"></a>
							<ul id="altselect-moto-diameter" class="row altselect" >
									<li>
										<span data-bind=""><?=__("None")?></span>
									</li>
							<?php foreach ($tire_diameter_collection as $item ):?>
											<li>
												<span data-bind="<?= $item["value"]?>"><?= $item["label"]?></span>
											</li>
							<?php endforeach;?> 
							</ul>
						</div>
					</div> 
				</div>
				
				
            </div>
        </div>
    </fieldset>
	
	<div class="row mt-20"><div class="col-12 text-center"> <img src="/pub/media/sportires/buscador/type_mark.png"></div></div>
	
    <div class="row col-md-12" >
        <div class="col-md-12">
            <button type="submit" class="btn-spt-1 action submit primary btn col-md-12" title="<?php  echo __('View Results') ?>"><span><?php echo __('Buscar') ?></span></button>
        </div>
    </div>
	
	





</form>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#moto-form');
        dataForm.mage('validation', {});

    });
	
</script>

<script>
    require(['jquery', 'jquery/ui'], function($){
        jQuery(document).ready( function() {

			$(".close").click(function(){ 
				$(".block.ui-dialog-content").dropdownDialog("close");
			});
			
			$("#altselect-moto-width span").click(function(){
				$("#moto-width-input").val($(this).data().bind);
				$("#moto_tire_width").val($(this).text());
				$("#altselect-moto-width span").removeClass("selected");
				$(this).addClass("selected");
				
				localStorage.setItem("m-width",$(this).data().bind);
				if($('div[data-block="dropdown-moto-width"]  .mage-dropdown-dialog').css('display') == 'block')
					$(".block-container-moto-width").dropdownDialog("close");
			});

			$("#altselect-moto-ratio span").click(function(){
				$("#moto-ratio-input").val($(this).data().bind);
				$("#moto_tire_ratio").val($(this).text());
				$("#altselect-moto-ratio span").removeClass("selected");
				$(this).addClass("selected");
				
				localStorage.setItem("m-ratio",$(this).data().bind);
				if($('div[data-block="dropdown-moto-ratio"]  .mage-dropdown-dialog').css('display') == 'block')
					$(".block-container-moto-ratio").dropdownDialog("close");
			});
			
			$("#altselect-moto-diameter span").click(function(){ 
				$("#moto-diameter-input").val($(this).data().bind);
				$("#moto_tire_diameter").val($(this).text());
				$("#altselect-moto-diameter span").removeClass("selected");
				$(this).addClass("selected");
				
				localStorage.setItem("m-diameter",$(this).data().bind);
				if($('div[data-block="dropdown-moto-diameter"]  .mage-dropdown-dialog').css('display') == 'block')
					$(".block-container-moto-diameter").dropdownDialog("close"); 
			});
			
        });
    });

				
				
</script>
<script>
    require(['jquery', 'jquery/ui'], function($){
        jQuery(".itm.filterproducts-tab-main .mage-dropdown-dialog").ready( function() {
			
			if(localStorage.getItem("m-width")){
				$("#altselect-moto-width span[data-bind='"+localStorage.getItem('m-width')+"']").trigger('click');
			}
			if(localStorage.getItem("m-ratio")){
				$("#altselect-moto-ratio span[data-bind='"+localStorage.getItem('m-ratio')+"']").trigger('click');
			}
			if(localStorage.getItem("m-diameter")){
				$("#altselect-moto-diameter span[data-bind='"+localStorage.getItem('m-diameter')+"']").trigger('click');
			}
		});
    });
</script>