<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$top_header_notification = $helper->getTopheadernotification();
?>
<span class="header-notification">
    <i class="fa fa-whatsapp" aria-hidden="true" style="font-size: 24px; color: #ff0000;"></i> <?php echo $top_header_notification; ?>
</span>
