<?php
/**
* CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the End User License Agreement (EULA)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* https://cedcommerce.com/license-agreement.txt
*
* @category    Ced
* @package     Ced_StorePickup
* @author      CedCommerce Core Team <connect@cedcommerce.com >
* @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
* @license      https://cedcommerce.com/license-agreement.txt
*/

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $shipment = $block->getShipment(); 

	  $storeId = $order->getStorePickupId();
	  if($storeId != '0'){
	  	$pickup_date = $order->getStorePickupDate();
	  	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      	$storeData = $objectManager->create('\Ced\StorePickup\Model\StoreInfo')->load($storeId);
      	$store_Name = $storeData->getStoreName();
      	$store_mgr_name = $storeData->getStoreManagerName();
      	$store_address = $storeData->getStoreAddress();
      	$store_city = $storeData->getStoreState();
      	$store_country = $storeData->getStoreCountry();
      	$country_name = $objectManager->create('\Magento\Directory\Model\Country')->load($store_country)->getName();
      	$storezip = $storeData->getStoreZcode();
      	
	  }
	  

 ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php /* @escapeNotVerified */ echo __('Track Order') ?>"><?php /* @escapeNotVerified */ echo __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?php echo $block->escapeHtml($order->getShippingDescription()) ?></strong>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?php /* @escapeNotVerified */ echo $_excl; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
            <?php endif; ?>
            <?php if ($order->getShippingDescription()=='Store Pickup - Store Pickup'): ?>
            	<?php if ($storeId>0){ ?>
            		<p>
            			<span><b><?php echo __('Store Name'); ?></b></span>
            			<span><?php echo $store_Name; ?></span>
            		</p>
            		<p>
            			<span><b><?php echo __('Store Address'); ?></b></span>
            			<span><?php echo $store_address; ?></span>
            		</p>
            		<p>
            			<span><b><?php echo __('Store City'); ?></b></span>
            			<span><?php echo $store_city; ?></span>
            		</p>
            		<p>
            			<span><b><?php echo __('Store Country'); ?></b></span>
            			<span><?php echo $country_name; ?></span>
            		</p>
            		<p>
            			<span><b><?php echo __('Store Zip Code'); ?></b></span>
            			<span><?php echo $storezip; ?></span>
            		</p>
            		<p>
            			<span><b><?php echo __('Store Pickup Date'); ?></b></span>
            			<span><?php echo $pickup_date; ?></span>
            		</p>
            	<?php } ?>
            	<?php endif; ?>	
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
        <?php endif; ?>
    </div>
</div>
